CREATE DATABASE IF NOT EXISTS blog;
USE blog;

CREATE TABLE posts (
	posts_id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP(),
    author_id INT NOT NULL,
    PRIMARY KEY(posts_id)
);

CREATE TABLE authors (
	author_id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY(author_id)
);
